---
language: python
services: docker

env:
  global:
    - ROLE_NAME: repo_ius
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME kietnguyen.$ROLE_NAME
  - cd kietnguyen.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
